"""Self-contained HTML formatter for lint results."""

from __future__ import annotations

import html as html_mod
from collections import defaultdict

from r2o_check import __version__
from r2o_check.config import Config
from r2o_check.engine import LintResult, Status

_STATUS_CLASS = {
    Status.PASS: "pass",
    Status.WARN: "warn",
    Status.FAIL: "fail",
    Status.ERROR: "error",
}

_STATUS_LABEL = {
    Status.PASS: "\u2714 PASS",
    Status.WARN: "\u26a0 WARN",
    Status.FAIL: "\u2718 FAIL",
    Status.ERROR: "ERROR",
}

_CSS = """\
body { font-family: -apple-system, BlinkMacSystemFont,
  "Segoe UI", Roboto, sans-serif; margin: 2em; color: #222; }
h1 { border-bottom: 2px solid #333; padding-bottom: 0.3em; }
.summary { display: flex; gap: 2em; margin: 1em 0; }
.summary .box { padding: 0.5em 1.5em; border-radius: 6px;
  font-size: 1.2em; font-weight: bold; }
.box.pass { background: #d4edda; color: #155724; }
.box.warn { background: #fff3cd; color: #856404; }
.box.fail { background: #f8d7da; color: #721c24; }
table { border-collapse: collapse; width: 100%; margin: 1em 0; }
th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
th { background: #f8f9fa; cursor: pointer; user-select: none; }
th:hover { background: #e9ecef; }
tr.pass td:first-child { color: #28a745; }
tr.warn td:first-child { color: #ffc107; }
tr.fail td:first-child { color: #dc3545; font-weight: bold; }
tr.error td:first-child { color: #dc3545; font-weight: bold; }
.fix { color: #666; font-style: italic; }
footer { margin-top: 2em; color: #999; font-size: 0.85em; }
"""

_JS = """\
document.addEventListener("DOMContentLoaded", function() {
  var table = document.getElementById("results");
  if (!table) return;
  var headers = table.querySelectorAll("th");
  headers.forEach(function(th, idx) {
    th.setAttribute("aria-sort", "none");
    th.addEventListener("click", function() {
      var tbody = table.querySelector("tbody");
      var rows = Array.from(tbody.querySelectorAll("tr"));
      var cur = th.getAttribute("aria-sort");
      var asc = cur !== "ascending";
      headers.forEach(function(h) {
        h.setAttribute("aria-sort", "none");
      });
      th.setAttribute("aria-sort", asc ? "ascending" : "descending");
      rows.sort(function(a, b) {
        var at = a.cells[idx].textContent.trim();
        var bt = b.cells[idx].textContent.trim();
        return asc ? at.localeCompare(bt) : bt.localeCompare(at);
      });
      rows.forEach(function(r) { tbody.appendChild(r); });
    });
  });
});
"""


def format_results_html(
    results: list[LintResult],
    config: Config,
) -> str:
    """Format results as self-contained HTML."""
    counts = {s: 0 for s in Status}
    for r in results:
        counts[r.status] += 1

    by_cat: dict[str, list[LintResult]] = defaultdict(list)
    for r in results:
        prefix = r.rule_id[:6]
        by_cat[prefix].append(r)

    rows: list[str] = []
    for cat in sorted(by_cat.keys()):
        for r in by_cat[cat]:
            cls = _STATUS_CLASS[r.status]
            lbl = _STATUS_LABEL[r.status]
            msg = html_mod.escape(r.message)
            fix = (
                f'<span class="fix">'
                f"{html_mod.escape(r.fix_hint)}</span>"
                if r.fix_hint
                else ""
            )
            rows.append(
                f'<tr class="{cls}">'
                f"<td>{lbl}</td>"
                f"<td><code>{r.rule_id}</code></td>"
                f"<td>{msg}</td>"
                f"<td>{fix}</td>"
                f"</tr>"
            )

    table = "\n".join(rows)

    return f"""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>r2o-check Report</title>
<style>{_CSS}</style>
</head>
<body>
<h1>r2o-check Lint Report</h1>
<div class="summary">
  <div class="box pass">{counts[Status.PASS]} passed</div>
  <div class="box warn">{counts[Status.WARN]} warnings</div>
  <div class="box fail">{counts[Status.FAIL]} failed</div>
</div>
<table id="results">
<thead><tr>
  <th aria-sort="none">Status</th>\
<th aria-sort="none">Rule</th>\
<th aria-sort="none">Message</th>\
<th aria-sort="none">Fix</th>
</tr></thead>
<tbody>
{table}
</tbody>
</table>
<footer>
  Generated by r2o-check v{__version__}
  (repo_type: {config.repo_type.value})
</footer>
<script>{_JS}</script>
</body>
</html>"""
