"""Markdown formatter for lint results (PR comments)."""

from __future__ import annotations

from collections import defaultdict

from r2o_check.config import Config
from r2o_check.engine import LintResult, Status

_STATUS_EMOJI = {
    Status.PASS: "\u2705",
    Status.WARN: "\u26a0\ufe0f",
    Status.FAIL: "\u274c",
    Status.ERROR: "\U0001f534",
}

# Rule ID prefix -> category name.
_CATEGORIES = {
    "R2OSTR": "Structure",
    "R2ONAM": "Naming",
    "R2OENV": "Environment",
    "R2OBLD": "Build",
    "R2OMOD": "Modules",
    "R2OVER": "Versions",
    "R2OECF": "ecFlow",
}


def _category(rule_id: str) -> str:
    for prefix, name in _CATEGORIES.items():
        if rule_id.startswith(prefix):
            return name
    return "Other"


def format_results_markdown(
    results: list[LintResult],
    config: Config,
) -> str:
    """Format results as Markdown for PR comments."""
    counts = {s: 0 for s in Status}
    for r in results:
        counts[r.status] += 1

    lines: list[str] = []
    lines.append("## r2o-check lint results\n")

    # Summary table.
    lines.append(
        f"| {_STATUS_EMOJI[Status.PASS]} Pass "
        f"| {_STATUS_EMOJI[Status.WARN]} Warn "
        f"| {_STATUS_EMOJI[Status.FAIL]} Fail "
        f"| Total |"
    )
    lines.append("|---|---|---|---|")
    lines.append(
        f"| {counts[Status.PASS]} "
        f"| {counts[Status.WARN]} "
        f"| {counts[Status.FAIL]} "
        f"| {len(results)} |"
    )
    lines.append("")

    # Group by category.
    by_cat: dict[str, list[LintResult]] = defaultdict(list)
    for r in results:
        by_cat[_category(r.rule_id)].append(r)

    for cat_name in sorted(by_cat.keys()):
        cat_results = by_cat[cat_name]
        cat_fails = sum(
            1 for r in cat_results
            if r.status in (Status.FAIL, Status.ERROR)
        )
        cat_warns = sum(
            1 for r in cat_results
            if r.status == Status.WARN
        )
        icon = (
            _STATUS_EMOJI[Status.FAIL] if cat_fails
            else _STATUS_EMOJI[Status.WARN] if cat_warns
            else _STATUS_EMOJI[Status.PASS]
        )

        lines.append(
            f"<details><summary>"
            f"{icon} <b>{cat_name}</b>"
            f" ({len(cat_results)} checks)"
            f"</summary>\n"
        )
        lines.append("| Status | Rule | Message |")
        lines.append("|---|---|---|")
        for r in cat_results:
            emoji = _STATUS_EMOJI[r.status]
            msg = r.message.replace("|", "\\|")
            lines.append(
                f"| {emoji} | `{r.rule_id}` | {msg} |"
            )
        lines.append("\n</details>\n")

    lines.append(
        "---\n"
        "*Generated by [r2o-check]"
        "(https://github.com/mansurjisan/r2o-check)"
        f" (repo_type: `{config.repo_type.value}`)*"
    )
    return "\n".join(lines)
